name: dosbox-staging
version: 0.82.2
summary: Open Source PC/MS-DOS emulator
description: |
  DOSBox is a DOS-emulator that uses the SDL-library which 
  makes DOSBox very easy to port to different platforms. DOSBox has 
  already been ported to many different platforms, such as Windows, BeOS, 
  Linux, MacOS X...
  
  DOSBox also emulates CPU:286/386 realmode/protected mode, 
  Directory FileSystem/XMS/EMS, Tandy/Hercules/CGA/EGA/VGA/VESA graphics, 
  a SoundBlaster/Gravis Ultra Sound card for excellent sound compatibility 
  with older games...
  
  You can "re-live" the good old days with the help of DOSBox, it 
  can run plenty of the old classics that don't run on your new computer!  
  
  DOSBox is totally free of charge and OpenSource.

grade: stable
confinement: strict
base: core22

architectures:
  - build-on: amd64
  - build-on: arm64
  - build-on: armhf

apps:
  dosbox-staging:
    command: usr/local/bin/dosbox
    plugs: [audio-playback, home, audio-record, desktop, desktop-legacy, wayland, x11, opengl, removable-media, joystick, network, network-bind]
    extensions: [gnome]
    environment: 
      HOME: $SNAP_REAL_HOME

parts:
  fluidsynth:
    source: https://github.com/FluidSynth/fluidsynth.git
    plugin: cmake
    source-tag: "v2.3.1"
    organize:
      usr/local/lib64/lib*.so*: usr/lib/
  mt:
    source: https://github.com/munt/munt.git
    plugin: cmake
    source-subdir: "mt32emu"
    organize:
      usr/local/lib/lib*.so*: usr/lib/
  dosbox-staging:
    after: [mt, fluidsynth]
    plugin: meson
    source: https://github.com/dosbox-staging/dosbox-staging/archive/refs/tags/v$SNAPCRAFT_PROJECT_VERSION.tar.gz
    build-packages:
      - libsdl2-dev
      - libsdl2-image-dev
      - libopus-dev
      - libopusfile-dev
      - cmake
      - build-essential
      - libsdl2-net-dev
      - libslirp-dev
      - pkg-config
      - meson
      - libpng-dev
    stage-packages:
      - libsdl2-2.0-0
      - libsdl2-image-2.0-0
      - libslirp0
      - libslang2
      - libglu1-mesa
      - libopusfile0
      - freeglut3
      - fluidsynth
      - libsdl2-net-2.0-0
    organize:
      usr/local/lib/*/lib*.so*: usr/lib/
      usr/local/lib/lib*.so*: usr/lib/
      usr/lib/*/libpulse.so.*: usr/lib/
      usr/lib/*/pulseaudio/libpulsecommon*: usr/lib/
    prime:
      - -share
      - -usr/share/doc
      - -usr/share/lintian
      - -usr/share/man
  cleanup:
    after: [fluidsynth, mt, dosbox-staging]
    plugin: nil
    build-snaps: [ gnome-42-2204 ]
    override-prime: |
      set -eux
      cd /snap/gnome-42-2204/current
      find . -type f,l -exec rm -f $CRAFT_PRIME/{} \;
